# Generated by Django 4.1.12 on 2024-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20)),
                ("month_year_number", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("subject", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="class_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=10)),
                ("division", models.CharField(max_length=1)),
                ("subjects", models.TextField(default="")),
                ("batch_year", models.TextField(default=0)),
                ("exam_result", models.DateTimeField(blank=True, null=True)),
                ("exam_name", models.TextField(blank=True, null=True)),
                ("exam_subject", models.TextField(blank=True, null=True)),
                ("attendance", models.DateTimeField(blank=True, null=True)),
                ("attendance_date", models.TextField(blank=True, null=True)),
                ("daily_class", models.DateTimeField(blank=True, null=True)),
                ("daily_class_date", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20)),
                ("exam_name", models.CharField(max_length=100)),
                (
                    "physics",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "chemistry",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "maths",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "physics_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "chemistry_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "maths_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20)),
                (
                    "physics",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "chemistry",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "maths",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("admission_no", models.CharField(max_length=20, unique=True)),
                ("phone_no", models.CharField(max_length=15, unique=True)),
                ("batch_year", models.TextField(default=0)),
                ("class_name", models.CharField(max_length=10)),
                ("division", models.CharField(max_length=1)),
                ("subjects", models.TextField()),
                ("class_group", models.TextField(default="")),
                ("school_name", models.TextField()),
                ("device_id", models.TextField(default="")),
                ("restricted", models.BooleanField(default=False)),
                (
                    "email_id",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("on_time", models.BooleanField(default=True)),
                ("voice", models.BooleanField(default=True)),
                ("nb_sub", models.BooleanField(default=True)),
                ("mob_net", models.BooleanField(default=True)),
                ("camera", models.BooleanField(default=True)),
                ("full_class", models.BooleanField(default=True)),
                ("activities", models.CharField(blank=True, max_length=100, null=True)),
                ("engagement", models.BooleanField(default=True)),
                (
                    "overall_performance_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "overall_performance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("admission_no", "date")},
            },
        ),
    ]
