# Generated by Django 4.2.5 on 2023-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
