# Generated by Django 4.2.5 on 2023-09-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0003_batchyear_classname_division_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='division',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subjects',
            new_name='subjects_name',
        ),
    ]
