# Generated by Django 4.2.5 on 2023-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0004_rename_division_division_division_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(default=0)),
            ],
        ),
    ]
