# Generated by Django 4.2.5 on 2023-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0007_alter_examresults_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='date',
            field=models.CharField(),
        ),
    ]
