# Generated by Django 4.2.5 on 2023-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0009_alter_examresults_chemistry_alter_examresults_maths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdates',
            name='overall_performance',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyupdates',
            name='overall_performance_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyupdates',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='activites',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='engagement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='full_class',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='mob_net',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='nb_sub',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='voice',
            field=models.BooleanField(default=True),
        ),
    ]
