# Generated by Django 4.2.5 on 2023-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0010_dailyupdates_overall_performance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyupdates',
            old_name='activites',
            new_name='activities',
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='overall_performance_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
