# Generated by Django 4.2.5 on 2023-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0013_student_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=1)),
                ('subjects', models.TextField(max_length=10)),
                ('batch_year', models.TextField(default=0)),
            ],
        ),
    ]
