# Generated by Django 4.2.5 on 2023-10-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0016_student_class_group_alter_student_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='batchYear',
        ),
        migrations.DeleteModel(
            name='className',
        ),
        migrations.DeleteModel(
            name='division',
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
        migrations.DeleteModel(
            name='table_names',
        ),
    ]
