# Generated by Django 4.1.12 on 2023-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0017_delete_batchyear_delete_classname_delete_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='month_year_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='overall_performance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
    ]
