# Generated by Django 4.1.12 on 2024-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0020_alter_student_admission_no_alter_student_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
