# Generated by Django 4.1.12 on 2024-02-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0021_student_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='logged_in',
        ),
    ]
