# Generated by Django 4.1.12 on 2024-02-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0022_remove_student_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
