# Generated by Django 4.1.12 on 2024-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0025_alter_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.TextField(default=''),
        ),
    ]
