# Generated by Django 4.1.12 on 2024-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0031_class_details_attendance_class_details_exam_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_details',
            name='leaderboard',
        ),
        migrations.AddField(
            model_name='class_details',
            name='attendance_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class_details',
            name='exam_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
