# Generated by Django 4.1.12 on 2024-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_student", "0034_attendance_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresults",
            name="chemistry",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="examresults",
            name="maths",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="examresults",
            name="physics",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
