# Generated by Django 4.1.12 on 2024-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "register_student",
            "0035_alter_examresults_chemistry_alter_examresults_maths_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="chemistry",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="maths",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="physics",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
