# Generated by Django 4.1.12 on 2024-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "register_student",
            "0036_alter_leaderboard_chemistry_alter_leaderboard_maths_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="class_details",
            name="daily_class",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
