# Generated by Django 4.1.12 on 2024-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_student", "0037_class_details_daily_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="class_details",
            name="daily_class_date",
            field=models.TextField(blank=True, null=True),
        ),
    ]
