# Generated by Django 4.1.12 on 2024-05-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_student", "0038_class_details_daily_class_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="class_details",
            name="exam_subject",
            field=models.TextField(blank=True, null=True),
        ),
    ]
