# Generated by Django 4.1.12 on 2024-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_student", "0039_class_details_exam_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresults",
            name="chemistry_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="examresults",
            name="maths_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="examresults",
            name="physics_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
