# Generated by Django 4.1.12 on 2023-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
