version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: gunicorn ecube_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
      # Add this line to expose port 443 for SSL
    depends_on:
      - web

volumes:
  static_volume:
