# Generated by Django 4.2.5 on 2023-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('admission_no', models.CharField()),
                ('phone_no', models.CharField(max_length=10)),
                ('class_name', models.CharField()),
                ('division', models.CharField(max_length=1)),
                ('subjects', models.TextField()),
                ('school_name', models.TextField()),
            ],
        ),
    ]
