# Generated by Django 4.2.5 on 2023-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0005_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField()),
                ('month_year_number', models.CharField()),
                ('date', models.DateField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField()),
                ('date', models.DateField()),
                ('on_time', models.BooleanField()),
                ('voice', models.BooleanField()),
                ('nb_sub', models.BooleanField()),
                ('mob_net', models.BooleanField()),
                ('camera', models.BooleanField()),
                ('full_class', models.BooleanField()),
                ('activites', models.CharField()),
                ('engagement', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField()),
                ('exam_name', models.CharField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
    ]
