# Generated by Django 4.2.5 on 2023-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0006_attendance_dailyupdates_examresults_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='exam_name',
            field=models.CharField(max_length=100),
        ),
    ]
