# Generated by Django 4.2.5 on 2023-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0008_alter_attendance_date_alter_dailyupdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='maths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
