# Generated by Django 4.2.5 on 2023-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0011_rename_activites_dailyupdates_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.TextField(default=''),
        ),
    ]
