# Generated by Django 4.2.5 on 2023-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0012_student_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
