# Generated by Django 4.2.5 on 2023-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0014_class_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='subjects',
            field=models.TextField(default=''),
        ),
    ]
