# Generated by Django 4.1.12 on 2023-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0018_alter_attendance_admission_no_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='device_id',
            field=models.TextField(default=''),
        ),
    ]
