# Generated by Django 4.1.12 on 2024-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0026_alter_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.TextField(blank=True),
        ),
    ]
