# Generated by Django 4.1.12 on 2024-02-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0027_alter_student_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_id',
        ),
    ]
