# Generated by Django 4.1.12 on 2024-02-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0029_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.TextField(default=''),
        ),
    ]
