# Generated by Django 4.1.12 on 2024-02-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0032_remove_class_details_leaderboard_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyupdates',
            unique_together={('admission_no', 'date')},
        ),
    ]
