# Generated by Django 4.1.12 on 2024-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_student", "0033_alter_dailyupdates_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="subject",
            field=models.CharField(default="", max_length=20),
        ),
    ]
