# Generated by Django 4.1.12 on 2024-02-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0004_alter_otp_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='phone_number',
            new_name='credientials',
        ),
    ]
