# Generated by Django 4.1.12 on 2024-02-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0005_rename_phone_number_otp_credientials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='credientials',
            field=models.TextField(max_length=256),
        ),
    ]
