# Generated by Django 4.1.12 on 2024-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0006_alter_otp_credientials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="access_token",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="token",
            name="refresh_token",
            field=models.CharField(max_length=255),
        ),
    ]
