# Generated by Django 4.1.12 on 2024-05-14 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0007_alter_token_access_token_alter_token_refresh_token"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="token",
            table="token",
        ),
    ]
