# Generated by Django 4.1.12 on 2023-10-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_auth', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_auth.admin')),
            ],
        ),
    ]
