# Generated by Django 4.1.12 on 2023-10-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_alter_chatroom_superuser_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='admission_no',
        ),
    ]
