# Generated by Django 4.1.12 on 2023-10-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0018_alter_attendance_admission_no_alter_attendance_date_and_more'),
        ('chat_system', '0003_rename_name_chatroom_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register_student.student'),
        ),
    ]
