# Generated by Django 4.1.12 on 2023-10-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0018_alter_attendance_admission_no_alter_attendance_date_and_more'),
        ('chat_system', '0004_alter_chatroom_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='register_student.student'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
