# Generated by Django 4.1.12 on 2023-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0007_alter_chatmessage_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.IntegerField(default=0),
        ),
    ]
