# Generated by Django 4.1.12 on 2023-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0011_alter_chatmessage_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(blank=True, default='Student', max_length=100, null=True),
        ),
    ]
