# Generated by Django 4.1.12 on 2023-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0012_alter_chatmessage_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='superuser',
            field=models.IntegerField(),
        ),
    ]
