# Generated by Django 4.1.12 on 2025-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
