# Generated by Django 4.1.12 on 2024-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcement", models.CharField(max_length=100)),
                ("upload_date", models.CharField(max_length=10)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="class_updates_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("batch_year", models.CharField(max_length=4)),
                ("division", models.CharField(max_length=1)),
                ("link", models.CharField(blank=True, max_length=100, null=True)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="recordings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("batch_year", models.CharField(max_length=4)),
                ("division", models.CharField(max_length=1)),
                ("subject", models.CharField(max_length=100)),
                (
                    "date",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("recording_link", models.TextField(blank=True, null=True)),
                ("video_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
