# Generated by Django 4.1.12 on 2023-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_updates_link',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
