# Generated by Django 4.1.12 on 2025-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_updates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class_updates_link",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
