# Generated by Django 4.1.12 on 2023-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0002_alter_class_updates_link_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_updates_link',
            name='class_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='class_updates_link',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
