# Generated by Django 4.1.12 on 2023-12-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0004_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_updates_link',
            name='class_time',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class_updates_link',
            name='date',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class_updates_link',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class_updates_link',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
