# Generated by Django 4.1.12 on 2023-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0005_alter_class_updates_link_class_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=4)),
                ('division', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('recording_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
