# Generated by Django 4.1.12 on 2023-12-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0006_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordings',
            name='topic',
        ),
    ]
