# Generated by Django 4.1.12 on 2023-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0007_remove_recordings_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
