# Generated by Django 4.1.12 on 2024-02-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0008_recordings_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_updates_link',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='class_updates_link',
            name='date',
        ),
        migrations.RemoveField(
            model_name='class_updates_link',
            name='subject',
        ),
    ]
