# Generated by Django 4.1.12 on 2024-01-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='logged_in',
        ),
    ]
