# Generated by Django 4.1.12 on 2023-11-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_updates_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=4)),
                ('division', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
