# Generated by Django 4.1.12 on 2023-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_updates', '0003_class_updates_link_class_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
